#!/bin/sh

# replace help message with new

echo 'replacing README help message'

help_message=$(uv run --no-project steamcb/cli.py -h)
file='README.md'

uv run - <<EOF
import re
from pathlib import Path

FILE = Path('${file}')
START = '\`\`\`console block=api'
END = '\`\`\`'

text: str
with open(FILE, 'r') as f:
    text = f.read()

text = re.sub(
    rf'{re.escape(START)}(.*?){re.escape(END)}',
    f"""{START}
${help_message}
{END}""",
    text,
    flags=re.DOTALL,
)

with open(FILE, 'w') as f:
    f.write(text)
EOF

git add ${file}
